export enum UrlStatus {
    PENDING = 'PENDING',
    FETCHED = 'FETCHED',
    PARSED = 'PARSED',
    SKIPPED_ROBOTS = 'SKIPPED_ROBOTS',
    SKIPPED_DUPLICATE = 'SKIPPED_DUPLICATE',
    SKIPPED_TOO_LARGE = 'SKIPPED_TOO_LARGE',
    SKIPPED_TOO_DEEP = 'SKIPPED_TOO_DEEP',
    FAILED = 'FAILED',
}